#!/bin/bash
#SBATCH -t 72:00:00
#SBATCH --ntasks-per-node=32
#SBATCH -c 4
#SBATCH -N 8
#SBATCH -J hBN_test
#SBATCH --account=hpc-prf-coopfst
#SBATCH -p largemem
##SBATCH -q express

export OMP_NUM_THREADS=4
export OMP_PLACES=cores
export OMP_PROC_BIND=true

module purge
module load chem/CP2K/2025.2-foss-2024a-gcc-openmpi-openblas

rm cp2k.out
srun /pc2/groups/hpc-prf-metdyn/metdyn02_Remi/cp2k/newcp2k/cp2k/exe/local/cp2k.psmp *inp >> cp2k.out
