#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH --ntasks-per-node=16
#SBATCH -c 8
#SBATCH -N 8
#SBATCH -J hBN_test
#SBATCH --account=hpc-prf-coopfst
#SBATCH -p normal
##SBATCH -q express

export OMP_NUM_THREADS=8
export OMP_PLACES=cores
export OMP_PROC_BIND=true

module purge
module load chem/CP2K/2025.2-foss-2024a-gcc-openmpi-openblas

rm cp2k.out
srun /pc2/groups/hpc-prf-metdyn/metdyn02_Remi/cp2k/newcp2k/cp2k/exe/local/cp2k.psmp *inp >> cp2k.out
